/**
 * FDC Food Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package macromacro.fdc.model

import org.joda.time.DateTime
import java.util.UUID

case class FoodReportInputFoods (
  id: Option[Int] = None,
  unit: Option[String] = None,
  portionDescription: Option[String] = None,
  portionCode: Option[String] = None,
  srCode: Option[Int] = None,
  srDescription: Option[String] = None,
  foodDescription: Option[String] = None,
  gramWeight: Option[Double] = None,
  surveyFlag: Option[Int] = None,
  amount: Option[Double] = None,
  sequenceNumber: Option[Int] = None
)
