/**
 * FDC Food Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package macromacro.fdc.model

import org.joda.time.DateTime
import java.util.UUID

case class FoodReportFoodComponents (
  id: Option[Int] = None,
  fdcId: Option[Int] = None,
  name: Option[String] = None,
  pctWeight: Option[Double] = None,
  isRefuse: Option[FoodReportFoodComponentsEnums.IsRefuse] = None,
  gramWeight: Option[Double] = None,
  dataPoints: Option[Double] = None,
  minYearAcquired: Option[String] = None
)

object FoodReportFoodComponentsEnums {

  type IsRefuse = IsRefuse.Value
  object IsRefuse extends Enumeration {
    val `Y` = Value("Y")
    val `N` = Value("N")
  }

}
