/**
 * FDC Food Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package macromacro.fdc.model

import org.joda.time.DateTime
import java.util.UUID

case class FoodReport (
  /* TODO */
  foodClass: Option[String] = None,
  /* TODO */
  description: Option[String] = None,
  foodNutrients: Option[FoodReportFoodNutrients] = None,
  foodComponents: Option[Seq[FoodReportFoodComponents]] = None,
  foodAttributes: Option[Seq[Any]] = None,
  tableAliasName: Option[String] = None,
  foodCode: Option[String] = None,
  startDate: Option[String] = None,
  endDate: Option[String] = None,
  wweiaFoodCategory: Option[FoodReportWweiaFoodCategory] = None,
  fdcId: Option[Int] = None,
  dataType: Option[String] = None,
  publicationDate: Option[String] = None,
  foodPortions: Option[Seq[FoodReportFoodPortions]] = None,
  inputFoods: Option[Seq[FoodReportInputFoods]] = None,
  changes: Option[String] = None
)
