/**
 * FDC Food Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package macromacro.fdc.model

import org.joda.time.DateTime
import java.util.UUID

case class SearchResponseFoodSearchCriteriaFoods (
  fdcId: Int,
  description: String,
  /* The scientific name of the food. */
  scientificName: Option[String] = None,
  /* Any other common names for the food. */
  commonNames: Option[String] = None,
  /* Any additional descriptions of the food. */
  additionalDescriptions: Option[Any] = None,
  /* The type of the food data */
  dataType: SearchResponseFoodSearchCriteriaFoodsEnums.DataType,
  /* A unique ID identifying the food within FNDDS. */
  foodCode: Option[String] = None,
  /* GTIN or UPC code identifying the food. */
  gtinUpc: String,
  /* Unique number assigned for foundation foods. */
  ndbNumber: Option[String] = None,
  /* Date the item was published to FDC. */
  publishedDate: String,
  /* Brand owner for the food. */
  brandOwner: Option[String] = None,
  /* The list of ingredients (as it appears on the product label). */
  ingredients: Option[String] = None,
  /* Fields that were found matching the criteria. */
  allHighlightFields: String,
  /* Relative score indicating how well the food matches the search criteria. */
  score: Double
)

object SearchResponseFoodSearchCriteriaFoodsEnums {

  type DataType = DataType.Value
  object DataType extends Enumeration {
    val SurveyFNDDS = Value("Survey (FNDDS)")
    val Branded = Value("Branded")
    val Foundation = Value("Foundation")
  }

}
