openapi: "3.0.2"
info:
  version: 1.0.0
  title: Macro Macro API
  description: An API that provides access to recipe and ingredient information, both user-generated and sourced from the USDA
  # termsOfService: http://swagger.io/terms/
  # contact:
  #   name: Swagger API Team
  #   email: apiteam@swagger.io
  #   url: http://swagger.io
  # license:
  #   name: Apache 2.0
  #   url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:5555
paths:
  /ingredients:
    get:
      description: |
        Returns all ingredients the user has saved
      operationId: findIngredients
      parameters:
        - name: sort
          in: query
          description: "sort key. options: recent"
          required: false
          style: form
          schema:
            type: string
        - name: limit
          in: query
          description: "maximum number of results to return. default: 10"
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: ingredient response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NamedMacros'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new ingredient.  Duplicates are allowed.
      operationId: createIngredient
      requestBody:
        description: Ingredient to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewIngredient'
      responses:
        '200':
          description: Macros of created ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamedMacros'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /ingredients/{uid}:
    get:
      description: Returns the ingredient specified by the UID
      operationId: findIngredientByUID
      parameters:
        - name: uid
          in: path
          description: UID of ingredient to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Macros of ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamedMacros'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /recipes:
    get:
      description: Returns all recipes the user has saved
      operationId: findRecipes
      parameters:
        - name: sort
          in: query
          description: "sort key. options: recent"
          required: false
          style: form
          schema:
            type: string
        - name: limit
          in: query
          description: "maximum number of results to return. default: 10"
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NamedMacros'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new recipe.  Duplicates are allowed.
      operationId: createRecipe
      requestBody:
        description: Recipe to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRecipe'
      responses:
        '200':
          description: Macros of created recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamedMacros'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /recipes/{uid}:
    get:
      description: Returns the recipe specified by the UID
      operationId: findRecipeByUID
      parameters:
        - name: uid
          in: path
          description: UID of recipe to fetch
          required: true
          schema:
            type: string
        - name: format
          in: query
          description: >-
            Format of the response. Options are 'macros' and 'full',
            default 'macros'
          required: false
          style: form
          schema:
            type: string
      responses:
        '200':
          description: recipe response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search:
    get:
      description: Search for ingredients and recipes by name
      operationId: searchByName
      parameters:
        - name: q
          in: query
          description: "search key"
          required: true
          style: form
          schema:
            type: string
        - name: sort
          in: query
          description: "sort key. options: recent"
          required: false
          style: form
          schema:
            type: string
        - name: limit
          in: query
          description: "maximum number of results to return. default: 10"
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: recipe response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NamedMacros'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:

    Macros:
      required:
        - fat
        - carbs
        - protein
        - calories
      properties:
        fat:
          type: number
        carbs:
          type: number
        protein:
          type: number
        calories:
          type: number

    NamedMacros:  # name this better
      allOf:
        - $ref: '#/components/schemas/Macros'
        - required:
          - uid
          - name
          - amount
          - unit
          properties:
            uid:
              type: string
            name:
              type: string
            amount:
              type: number
            unit:
              type: string

    NewIngredient:
      allOf:
        - $ref: '#/components/schemas/Macros'
        - required:
          - name
          - amount
          - unit
      properties:
        name:
          type: string
        amount:
          type: number
        unit:
          type: string

    AmountOfIngredient:
      required:
        - uid
        - amount
      properties:
        uid:
          type: string
        amount:
          type: number

    AmountOfNamedMacros:
      required:
        - namedMacros
        - amount
      properties:
        namedMacros:
          $ref: '#/components/schemas/NamedMacros'
        amount:
          type: number

    NewRecipe:
      required:
        - name
        - foods
        - totalSize
        - portionSize
        - unit
      properties:
        name:
          type: string
        foods:
          type: array
          items:
            $ref: '#/components/schemas/AmountOfIngredient'
        amount:
          type: number
        portionSize:
          type: number
        unit:
          type: string

    Recipe:
      allOf:
        - $ref: '#/components/schemas/NamedMacros'
        - required:
          - foods
          - portionSize
          properties:
            foods:
              type: array
              items:
                $ref: '#/components/schemas/AmountOfNamedMacros'
            portionSize:
              type: number

    Meal:
      required:
        - uid
        - foods
      properties:
        foods:
          type: array
          items:
            $ref: '#/components/schemas/AmountOfNamedMacros'

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
