# Not at all ready yet
# For use with flexible environment, eventually, if flex env ever gets search

# FROM gcr.io/google-appengine/jetty
# COPY target/scala-2.12/macro-macro_2.12-0.1.0-SNAPSHOT.war /var/lib/jetty/webapps/
