// tslint:disable
/**
 * Macro Macro API
 * An API that provides access to recipe and ingredient information, both user-generated and sourced from the USDA
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AmountOfIngredient
 */
export interface AmountOfIngredient {
    /**
     * 
     * @type {string}
     * @memberof AmountOfIngredient
     */
    uid: string;
    /**
     * 
     * @type {number}
     * @memberof AmountOfIngredient
     */
    amount: number;
}

export function AmountOfIngredientFromJSON(json: any): AmountOfIngredient {
    return AmountOfIngredientFromJSONTyped(json, false);
}

export function AmountOfIngredientFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmountOfIngredient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uid': json['uid'],
        'amount': json['amount'],
    };
}

export function AmountOfIngredientToJSON(value?: AmountOfIngredient): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uid': value.uid,
        'amount': value.amount,
    };
}


