// tslint:disable
/**
 * Macro Macro API
 * An API that provides access to recipe and ingredient information, both user-generated and sourced from the USDA
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NamedMacros,
    NamedMacrosFromJSON,
    NamedMacrosFromJSONTyped,
    NamedMacrosToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {Array<NamedMacros>}
     * @memberof InlineResponse200
     */
    recipes: Array<NamedMacros>;
    /**
     * 
     * @type {Array<NamedMacros>}
     * @memberof InlineResponse200
     */
    ingredients: Array<NamedMacros>;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recipes': (json['recipes'] as Array<any>).map(NamedMacrosFromJSON),
        'ingredients': (json['ingredients'] as Array<any>).map(NamedMacrosFromJSON),
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recipes': (value.recipes as Array<any>).map(NamedMacrosToJSON),
        'ingredients': (value.ingredients as Array<any>).map(NamedMacrosToJSON),
    };
}


