/**
 * Macro Macro API
 * An API that provides access to recipe and ingredient information, both user-generated and sourced from the USDA
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@openapitools.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

package org.openapitools.server.model

import com.macromacro.schema.CompleteFood

case class NamedMacros(

  uid: String, // TODO should only SavedNamedMacros have a uid?

  name: String,

  fat: BigDecimal,

  carbs: BigDecimal,

  protein: BigDecimal,

  calories: BigDecimal,

  amount: BigDecimal,

  unit: String) {

  def toCompleteFood: CompleteFood = {
    CompleteFood(this.uid, this.name, this.fat, this.carbs, this.protein, this.calories, this.amount, this.unit)
  }
}

object NamedMacros {
  def fromCompleteFood(food: CompleteFood): NamedMacros = {
    NamedMacros(food.uid, food.name, food.fat, food.carbs, food.protein, food.calories, food.amount, food.unit)
  }
}

case class IncompleteNamedMacros(

  uid: String, // TODO should only SavedNamedMacros have a uid?

  name: String,

  fat: Option[BigDecimal],

  carbs: Option[BigDecimal],

  protein: Option[BigDecimal],

  calories: Option[BigDecimal],

  amount: BigDecimal,

  unit: String) {

  private def makeCompleteMacros(
    thisFat: Option[BigDecimal] = fat,
    thisCarbs: Option[BigDecimal] = carbs,
    thisProtein: Option[BigDecimal] = protein,
    thisCalories: Option[BigDecimal] = calories) = {
    NamedMacros(uid, name, thisFat.get, thisCarbs.get, thisProtein.get, thisCalories.get, amount, unit)
  }

  def toComplete: Option[NamedMacros] = {
    (fat, carbs, protein, calories) match {
      case (Some(f), Some(c), Some(p), Some(kc)) => Some(makeCompleteMacros())
      case (Some(f), Some(c), Some(p), None) => Some(makeCompleteMacros(thisCalories = Option(f * 9 + c * 4 + p * 4)))
      case (Some(f), Some(c), None, Some(kc)) => Some(makeCompleteMacros(thisProtein = Option((kc - (f * 9 + c * 4)) / 4)))
      case (Some(f), None, Some(p), Some(kc)) => Some(makeCompleteMacros(thisCarbs = Option((kc - (f * 9 + p * 4)) / 4)))
      case (None, Some(c), Some(p), Some(kc)) => Some(makeCompleteMacros(thisFat = Option((kc - (c * 4 + p * 4)) / 9)))
      case _ => None
    }
  }
}
