/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Macro Macro API
 * An API that provides access to recipe and ingredient information, both user-generated and sourced from the USDA
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost:8080/Default".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 *
 * @export
 * @interface AmountOfIngredient
 */
export interface AmountOfIngredient {
    /**
     *
     * @type {string}
     * @memberof AmountOfIngredient
     */
    uid: string;
    /**
     *
     * @type {number}
     * @memberof AmountOfIngredient
     */
    amount: number;
}

/**
 *
 * @export
 * @interface AmountOfNamedMacros
 */
export interface AmountOfNamedMacros {
    /**
     *
     * @type {NamedMacros}
     * @memberof AmountOfNamedMacros
     */
    namedMacros: NamedMacros;
    /**
     *
     * @type {number}
     * @memberof AmountOfNamedMacros
     */
    amount: number;
}

/**
 *
 * @export
 * @interface Macros
 */
export interface Macros {
    /**
     *
     * @type {number}
     * @memberof Macros
     */
    fat: number;
    /**
     *
     * @type {number}
     * @memberof Macros
     */
    carbs: number;
    /**
     *
     * @type {number}
     * @memberof Macros
     */
    protein: number;
    /**
     *
     * @type {number}
     * @memberof Macros
     */
    calories: number;
}

/**
 *
 * @export
 * @interface Meal
 */
export interface Meal {
    /**
     *
     * @type {string}
     * @memberof Meal
     */
    uid: string;
    /**
     *
     * @type {Array<AmountOfNamedMacros>}
     * @memberof Meal
     */
    foods: Array<AmountOfNamedMacros>;
}

/**
 *
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     *
     * @type {number}
     * @memberof ApiError
     */
    code: number;
    /**
     *
     * @type {string}
     * @memberof ApiError
     */
    message: string;
}

/**
 *
 * @export
 * @interface NamedMacros
 */
export interface NamedMacros extends Macros {
    /**
     *
     * @type {string}
     * @memberof NamedMacros
     */
    uid: string;
    /**
     *
     * @type {string}
     * @memberof NamedMacros
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof NamedMacros
     */
    amount: number;
    /**
     *
     * @type {string}
     * @memberof NamedMacros
     */
    unit: string;
}

/**
 *
 * @export
 * @interface NewIngredient
 */
export interface NewIngredient extends Macros {
    /**
     *
     * @type {string}
     * @memberof NewIngredient
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof NewIngredient
     */
    amount: number;
    /**
     *
     * @type {string}
     * @memberof NewIngredient
     */
    unit: string;
}

/**
 *
 * @export
 * @interface NewRecipe
 */
export interface NewRecipe {
    /**
     *
     * @type {string}
     * @memberof NewRecipe
     */
    name: string;
    /**
     *
     * @type {Array<AmountOfIngredient>}
     * @memberof NewRecipe
     */
    foods: Array<AmountOfIngredient>;
    /**
     *
     * @type {number}
     * @memberof NewRecipe
     */
    amount: number;
    /**
     *
     * @type {number}
     * @memberof NewRecipe
     */
    portionSize: number;
    /**
     *
     * @type {string}
     * @memberof NewRecipe
     */
    unit: string;
}

/**
 *
 * @export
 * @interface Recipe
 */
export interface Recipe extends NamedMacros {
    /**
     *
     * @type {Array<AmountOfNamedMacros>}
     * @memberof Recipe
     */
    foods: Array<AmountOfNamedMacros>;
    /**
     *
     * @type {number}
     * @memberof Recipe
     */
    portionSize: number;
}


/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new ingredient.  Duplicates are allowed.
         * @param {NewIngredient} newIngredient Ingredient to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createIngredient(newIngredient: NewIngredient, options: any = {}): FetchArgs {
            // verify required parameter 'newIngredient' is not null or undefined
            if (newIngredient === null || newIngredient === undefined) {
                throw new RequiredError('newIngredient','Required parameter newIngredient was null or undefined when calling createIngredient.');
            }
            const localVarPath = `/ingredients`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"NewIngredient" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(newIngredient || {}) : (newIngredient || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new recipe.  Duplicates are allowed.
         * @param {NewRecipe} newRecipe Recipe to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRecipe(newRecipe: NewRecipe, options: any = {}): FetchArgs {
            // verify required parameter 'newRecipe' is not null or undefined
            if (newRecipe === null || newRecipe === undefined) {
                throw new RequiredError('newRecipe','Required parameter newRecipe was null or undefined when calling createRecipe.');
            }
            const localVarPath = `/recipes`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'POST' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"NewRecipe" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(newRecipe || {}) : (newRecipe || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the ingredient specified by the UID
         * @param {string} uid UID of ingredient to fetch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findIngredientByUID(uid: string, options: any = {}): FetchArgs {
            // verify required parameter 'uid' is not null or undefined
            if (uid === null || uid === undefined) {
                throw new RequiredError('uid','Required parameter uid was null or undefined when calling findIngredientByUID.');
            }
            const localVarPath = `/ingredients/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all ingredients the user has saved
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findIngredients(sort?: string, limit?: number, options: any = {}): FetchArgs {
            const localVarPath = `/ingredients`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the recipe specified by the UID
         * @param {string} uid UID of recipe to fetch
         * @param {string} [format] Format of the response. Options are &#39;macros&#39; and &#39;full&#39;, default &#39;macros&#39;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findRecipeByUID(uid: string, format?: string, options: any = {}): FetchArgs {
            // verify required parameter 'uid' is not null or undefined
            if (uid === null || uid === undefined) {
                throw new RequiredError('uid','Required parameter uid was null or undefined when calling findRecipeByUID.');
            }
            const localVarPath = `/recipes/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all recipes the user has saved
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findRecipes(sort?: string, limit?: number, options: any = {}): FetchArgs {
            const localVarPath = `/recipes`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search for ingredients and recipes by name
         * @param {string} q search key
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchByName(q: string, sort?: string, limit?: number, options: any = {}): FetchArgs {
            // verify required parameter 'q' is not null or undefined
            if (q === null || q === undefined) {
                throw new RequiredError('q','Required parameter q was null or undefined when calling searchByName.');
            }
            const localVarPath = `/search`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a new ingredient.  Duplicates are allowed.
         * @param {NewIngredient} newIngredient Ingredient to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createIngredient(newIngredient: NewIngredient, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<NamedMacros> {
            console.log(`creating ${newIngredient.name}`)
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).createIngredient(newIngredient, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Creates a new recipe.  Duplicates are allowed.
         * @param {NewRecipe} newRecipe Recipe to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRecipe(newRecipe: NewRecipe, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<NamedMacros> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).createRecipe(newRecipe, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Returns the ingredient specified by the UID
         * @param {string} uid UID of ingredient to fetch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findIngredientByUID(uid: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<NamedMacros> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).findIngredientByUID(uid, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Returns all ingredients the user has saved
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findIngredients(sort?: string, limit?: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<NamedMacros>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).findIngredients(sort, limit, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Returns the recipe specified by the UID
         * @param {string} uid UID of recipe to fetch
         * @param {string} [format] Format of the response. Options are &#39;macros&#39; and &#39;full&#39;, default &#39;macros&#39;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findRecipeByUID(uid: string, format?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Recipe> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).findRecipeByUID(uid, format, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Returns all recipes the user has saved
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findRecipes(sort?: string, limit?: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<NamedMacros>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).findRecipes(sort, limit, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Search for ingredients and recipes by name
         * @param {string} q search key
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchByName(q: string, sort?: string, limit?: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<NamedMacros[]> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).searchByName(q, sort, limit, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Creates a new ingredient.  Duplicates are allowed.
         * @param {NewIngredient} newIngredient Ingredient to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createIngredient(newIngredient: NewIngredient, options?: any) {
            return DefaultApiFp(configuration).createIngredient(newIngredient, options)(fetch, basePath);
        },
        /**
         * Creates a new recipe.  Duplicates are allowed.
         * @param {NewRecipe} newRecipe Recipe to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRecipe(newRecipe: NewRecipe, options?: any) {
            return DefaultApiFp(configuration).createRecipe(newRecipe, options)(fetch, basePath);
        },
        /**
         * Returns the ingredient specified by the UID
         * @param {string} uid UID of ingredient to fetch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findIngredientByUID(uid: string, options?: any) {
            return DefaultApiFp(configuration).findIngredientByUID(uid, options)(fetch, basePath);
        },
        /**
         * Returns all ingredients the user has saved
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findIngredients(sort?: string, limit?: number, options?: any) {
            return DefaultApiFp(configuration).findIngredients(sort, limit, options)(fetch, basePath);
        },
        /**
         * Returns the recipe specified by the UID
         * @param {string} uid UID of recipe to fetch
         * @param {string} [format] Format of the response. Options are &#39;macros&#39; and &#39;full&#39;, default &#39;macros&#39;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findRecipeByUID(uid: string, format?: string, options?: any) {
            return DefaultApiFp(configuration).findRecipeByUID(uid, format, options)(fetch, basePath);
        },
        /**
         * Returns all recipes the user has saved
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findRecipes(sort?: string, limit?: number, options?: any) {
            return DefaultApiFp(configuration).findRecipes(sort, limit, options)(fetch, basePath);
        },
        /**
         * Search for ingredients and recipes by name
         * @param {string} q search key
         * @param {string} [sort] sort key. options: recent
         * @param {number} [limit] maximum number of results to return. default: 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchByName(q: string, sort?: string, limit?: number, options?: any) {
            return DefaultApiFp(configuration).searchByName(q, sort, limit, options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Creates a new ingredient.  Duplicates are allowed.
     * @param {NewIngredient} newIngredient Ingredient to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createIngredient(newIngredient: NewIngredient, options?: any) {
        return DefaultApiFp(this.configuration).createIngredient(newIngredient, options)(this.fetch, this.basePath);
    }

    /**
     * Creates a new recipe.  Duplicates are allowed.
     * @param {NewRecipe} newRecipe Recipe to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createRecipe(newRecipe: NewRecipe, options?: any) {
        return DefaultApiFp(this.configuration).createRecipe(newRecipe, options)(this.fetch, this.basePath);
    }

    /**
     * Returns the ingredient specified by the UID
     * @param {string} uid UID of ingredient to fetch
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public findIngredientByUID(uid: string, options?: any) {
        return DefaultApiFp(this.configuration).findIngredientByUID(uid, options)(this.fetch, this.basePath);
    }

    /**
     * Returns all ingredients the user has saved
     * @param {string} [sort] sort key. options: recent
     * @param {number} [limit] maximum number of results to return. default: 10
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public findIngredients(sort?: string, limit?: number, options?: any) {
        return DefaultApiFp(this.configuration).findIngredients(sort, limit, options)(this.fetch, this.basePath);
    }

    /**
     * Returns the recipe specified by the UID
     * @param {string} uid UID of recipe to fetch
     * @param {string} [format] Format of the response. Options are &#39;macros&#39; and &#39;full&#39;, default &#39;macros&#39;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public findRecipeByUID(uid: string, format?: string, options?: any) {
        return DefaultApiFp(this.configuration).findRecipeByUID(uid, format, options)(this.fetch, this.basePath);
    }

    /**
     * Returns all recipes the user has saved
     * @param {string} [sort] sort key. options: recent
     * @param {number} [limit] maximum number of results to return. default: 10
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public findRecipes(sort?: string, limit?: number, options?: any) {
        return DefaultApiFp(this.configuration).findRecipes(sort, limit, options)(this.fetch, this.basePath);
    }

    /**
     * Search for ingredients and recipes by name
     * @param {string} q search key
     * @param {string} [sort] sort key. options: recent
     * @param {number} [limit] maximum number of results to return. default: 10
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchByName(q: string, sort?: string, limit?: number, options?: any) {
        return DefaultApiFp(this.configuration).searchByName(q, sort, limit, options)(this.fetch, this.basePath);
    }

}

