export const SELECT_DATASOURCE = 'ADD_DATASOURCE';
export const FOODSEARCH_INPUT = 'FOODSEARCH_INPUT';
export const FOODSEARCH_SUBMIT = 'FOODSEARCH_SUBMIT';
export const FOODDETAILS_CLICK = 'FOODDETAILS_CLICK';
export const FOODTRACK_CLICK = 'FOODTRACK_CLICK';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_RECIPE = 'ADD_RECIPE';
