/* export enum ActionTypeKeys {
 *   ADDINGREDIENT = '_ADDINGREDIENT',
 *   ADDRECIPE = '_ADDRECIPE',
 *   OTHER_ACTION = "__any_other_action_type__"
 * }
 */

export const SELECT_DATASOURCE = 'ADD_DATASOURCE';
export type SELECT_DATASOURCE = typeof SELECT_DATASOURCE;

export const FOODSEARCH_INPUT = 'FOODSEARCH_INPUT';
export type FOODSEARCH_INPUT = typeof FOODSEARCH_INPUT;

export const FOODSEARCH_SUBMIT = 'FOODSEARCH_SUBMIT';
export type FOODSEARCH_SUBMIT = typeof FOODSEARCH_SUBMIT;

export const FOODDETAILS_CLICK = 'FOODDETAILS_CLICK';
export type FOODDETAILS_CLICK = typeof FOODDETAILS_CLICK;

export const FOODTRACK_CLICK = 'FOODTRACK_CLICK';
export type FOODTRACK_CLICK = typeof FOODTRACK_CLICK;

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export type ADD_INGREDIENT = typeof ADD_INGREDIENT;

export const ADD_RECIPE = 'ADD_RECIPE';
export type ADD_RECIPE = typeof ADD_RECIPE;
