// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorItem
 */
export interface ErrorItem {
    /**
     * 
     * @type {number}
     * @memberof ErrorItem
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorItem
     */
    parameter?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorItem
     */
    message?: string;
}

export function ErrorItemFromJSON(json: any): ErrorItem {
    return {
        'status': !exists(json, 'status') ? undefined : json['status'],
        'parameter': !exists(json, 'parameter') ? undefined : json['parameter'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorItemToJSON(value?: ErrorItem): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'status': value.status,
        'parameter': value.parameter,
        'message': value.message,
    };
}


