// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ErrorResponseErrors,
    ErrorResponseErrorsFromJSON,
    ErrorResponseErrorsToJSON,
} from './';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {ErrorResponseErrors}
     * @memberof ErrorResponse
     */
    errors?: ErrorResponseErrors;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
    return {
        'errors': !exists(json, 'errors') ? undefined : ErrorResponseErrorsFromJSON(json['errors']),
    };
}

export function ErrorResponseToJSON(value?: ErrorResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'errors': ErrorResponseErrorsToJSON(value.errors),
    };
}


