// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * ingredients (Branded Food Products report only)
 * @export
 * @interface FoodFoodIng
 */
export interface FoodFoodIng {
    /**
     * list of ingredients
     * @type {string}
     * @memberof FoodFoodIng
     */
    desc: string;
    /**
     * date ingredients were last updated by company
     * @type {string}
     * @memberof FoodFoodIng
     */
    upd: string;
}

export function FoodFoodIngFromJSON(json: any): FoodFoodIng {
    return {
        'desc': json['desc'],
        'upd': json['upd'],
    };
}

export function FoodFoodIngToJSON(value?: FoodFoodIng): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'desc': value.desc,
        'upd': value.upd,
    };
}


