// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    FoodFood,
    FoodFoodFromJSON,
    FoodFoodToJSON,
} from './';

/**
 * the food report
 * @export
 * @interface Food
 */
export interface Food {
    /**
     * 
     * @type {FoodFood}
     * @memberof Food
     */
    food: FoodFood;
}

export function FoodFromJSON(json: any): Food {
    return {
        'food': FoodFoodFromJSON(json['food']),
    };
}

export function FoodToJSON(value?: Food): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'food': FoodFoodToJSON(value.food),
    };
}


