// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    Food,
    FoodFromJSON,
    FoodToJSON,
} from './';

/**
 * 
 * @export
 * @interface FoodReport
 */
export interface FoodReport {
    /**
     * the list of foods reported for a request
     * @type {Array<Food>}
     * @memberof FoodReport
     */
    foods: Array<Food>;
    /**
     * Number of foods requested and processed
     * @type {number}
     * @memberof FoodReport
     */
    count: number;
    /**
     * Number of requested foods not found in the database
     * @type {number}
     * @memberof FoodReport
     */
    notfound: number;
    /**
     * API Version
     * @type {number}
     * @memberof FoodReport
     */
    api: number;
}

export function FoodReportFromJSON(json: any): FoodReport {
    return {
        'foods': (json['foods'] as Array<any>).map(FoodFromJSON),
        'count': json['count'],
        'notfound': json['notfound'],
        'api': json['api'],
    };
}

export function FoodReportToJSON(value?: FoodReport): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'foods': (value.foods as Array<any>).map(FoodToJSON),
        'count': value.count,
        'notfound': value.notfound,
        'api': value.api,
    };
}


