// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * list of measures reported for a nutrient
 * @export
 * @interface NutrientsMeasures
 */
export interface NutrientsMeasures {
    /**
     * name of the measure, e.g. \"large\"
     * @type {string}
     * @memberof NutrientsMeasures
     */
    label: string;
    /**
     * equivalent of the measure expressed as an eunit
     * @type {number}
     * @memberof NutrientsMeasures
     */
    eqv: number;
    /**
     * Unit in with the equivalent amount is expressed. Usually either gram (g) or milliliter (ml) 
     * @type {string}
     * @memberof NutrientsMeasures
     */
    eunit: string;
    /**
     * gram equivalent value of the measure
     * @type {string}
     * @memberof NutrientsMeasures
     */
    value: string;
    /**
     * Dunno, not in the docs
     * @type {number}
     * @memberof NutrientsMeasures
     */
    qty?: number;
}

export function NutrientsMeasuresFromJSON(json: any): NutrientsMeasures {
    return {
        'label': json['label'],
        'eqv': json['eqv'],
        'eunit': json['eunit'],
        'value': json['value'],
        'qty': !exists(json, 'qty') ? undefined : json['qty'],
    };
}

export function NutrientsMeasuresToJSON(value?: NutrientsMeasures): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'label': value.label,
        'eqv': value.eqv,
        'eunit': value.eunit,
        'value': value.value,
        'qty': value.qty,
    };
}


