// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    SearchList,
    SearchListFromJSON,
    SearchListToJSON,
} from './';

/**
 * A search response consists of information about the results of the search such as the total hits matching the query and the starting and ending points in the results list, followed by a list of foods. Metadata for each food in the returned list includes the food\'s description (name) and NDBno. 
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * 
     * @type {SearchList}
     * @memberof SearchResponse
     */
    list: SearchList;
}

export function SearchResponseFromJSON(json: any): SearchResponse {
    return {
        'list': SearchListFromJSON(json['list']),
    };
}

export function SearchResponseToJSON(value?: SearchResponse): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'list': SearchListToJSON(value.list),
    };
}


