// tslint:disable
/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    SearchItem,
    SearchItemFromJSON,
    SearchItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface SearchList
 */
export interface SearchList {
    /**
     * terms requested and used in the search
     * @type {string}
     * @memberof SearchList
     */
    q?: string;
    /**
     * Standard Release version of the data being reported
     * @type {string}
     * @memberof SearchList
     */
    sr?: string;
    /**
     * undocumented. anecdotally, has returned \"all\"
     * @type {string}
     * @memberof SearchList
     */
    ds?: string;
    /**
     * beginning item in the list
     * @type {number}
     * @memberof SearchList
     */
    start?: number;
    /**
     * last item in the list
     * @type {number}
     * @memberof SearchList
     */
    end?: number;
    /**
     * total # of items returned by the search 
     * @type {number}
     * @memberof SearchList
     */
    total?: number;
    /**
     * food group to which the food belongs
     * @type {string}
     * @memberof SearchList
     */
    group?: string;
    /**
     * requested sort order (r=relevance or n=name)
     * @type {string}
     * @memberof SearchList
     */
    sort?: SearchListSortEnum;
    /**
     * individual items on the list
     * @type {Array<SearchItem>}
     * @memberof SearchList
     */
    item?: Array<SearchItem>;
}

export function SearchListFromJSON(json: any): SearchList {
    return {
        'q': !exists(json, 'q') ? undefined : json['q'],
        'sr': !exists(json, 'sr') ? undefined : json['sr'],
        'ds': !exists(json, 'ds') ? undefined : json['ds'],
        'start': !exists(json, 'start') ? undefined : json['start'],
        'end': !exists(json, 'end') ? undefined : json['end'],
        'total': !exists(json, 'total') ? undefined : json['total'],
        'group': !exists(json, 'group') ? undefined : json['group'],
        'sort': !exists(json, 'sort') ? undefined : json['sort'],
        'item': !exists(json, 'item') ? undefined : (json['item'] as Array<any>).map(SearchItemFromJSON),
    };
}

export function SearchListToJSON(value?: SearchList): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'q': value.q,
        'sr': value.sr,
        'ds': value.ds,
        'start': value.start,
        'end': value.end,
        'total': value.total,
        'group': value.group,
        'sort': value.sort,
        'item': value.item === undefined ? undefined : (value.item as Array<any>).map(SearchItemToJSON),
    };
}

/**
* @export
* @enum {string}
*/
export enum SearchListSortEnum {
    R = 'r',
    N = 'n'
}


