/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.macromacro.usda

case class ReportError(error: String)

case class FoodReport(
  // this error condition
  // {
  //   "foods": [
  //     {
  //       "error": "No data for ndbno 40"
  //     }
  //   ],
  //   "count": 1,
  //   "notfound": 1,
  //   "api": 2.0
  // }

  /** the list of foods reported for a request */
  foods: List[Either[ReportError, Food]],
  /** Number of foods requested and processed */
  count: Number,
  /** Number of requested foods not found in the database */
  notfound: Number,
  /** API Version */
  api: Number)
