/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.macromacro.usda

case class FoodFood(
  // report type
  `type`: String,
  // Release version of the data being reported
  sr: String,
  // metadata elements for the food being reported
  desc: Desc,
  // ingredients (Branded Food Products report only)
  ing: Option[FoodFoodIng] = None,
  // metadata elements for each nutrient included in the food report
  nutrients: List[Nutrients])
