/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.macromacro.usda

case class Nutrients(
  // nutrient number (nutrient_no) for the nutrient
  nutrient_id: String,
  // nutrient name
  name: String,
  // Indicator of how the value was derived
  derivation: String,
  // unit of measure for this nutrient
  unit: String,
  // 100 g equivalent value of the nutrient
  value: String,
  // # of data points
  dp: Option[String] = None,
  // standard error
  se: Option[String] = None,
  // list of measures reported for a nutrient
  measures: List[NutrientsMeasures])
