/**
 * USDA Report API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.macromacro.usda

case class NutrientsMeasures(
  // name of the measure, e.g. \"large\"
  label: String,
  // equivalent of the measure expressed as an eunit
  eqv: Double,
  // Unit in with the equivalent amount is expressed. Usually either gram (g) or milliliter (ml)
  eunit: String,
  // gram equivalent value of the measure
  value: String,
  // Dunno, not in the docs
  qty: Option[Double] = None)
